name: actions

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: docker-compose -f docker-compose.yml up -d --build
      - name: Test
        run: 	docker-compose exec -T go go test ./test -v
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: docker-compose -f docker-compose.yml up -d --build
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
