name: Go-Testing

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: docker-compose -f docker-compose.yml up -d --build
      - name: Test
        run: 	docker-compose exec -T go go test ./test -v
